### ISSUE TITLE
Various spelling mistakes in code....

### ISSUE THREAD

**Issue by mrb1090** [rohitsinghsalyan/polygeohasher#2]
Just tried this repo.  Works well, except for the following:

When trying the example, was getting a key error when attempting to create the geohash geometry dataframe (geo_df = ...).  

Error was traced to misspelling of "opitimized_geohash_list", which should be "optimized_geohash_list"

Also, for consistency's sake, would stick with "optimize..." throughout the codebase rather than intermingle "optimize..." and "optimise.."

Best,

Mike

**Comment by rohitsinghsalyan** [comment]
Hi, Mike 
thanks for raising these issues. Will work on it and release the new version soon.

**Comment by rohitsinghsalyan** [comment]
I have corrected the issues, please check if there are any issue. post that will close this issue. Thanks
